### ISSUE TITLE
prerequisite policy (dammit haus)

### ISSUE THREAD

**Issue by alnewkirk** [dhoss/Grimlock#18]
alnewkirk@alnewkirk:~/Repos/alnewkirk/Grimlock$ dbicadmin -Ilib --schema=Grimlock::Schema   --connect='["dbi:SQLite:grimlock.db", "", ""]' --deploy
Performing action deploy...
DBIx::Class::Schema::throw_exception(): Feature bundle "5.12" is not supported by Perl 5.10.1 at /usr/local/share/perl/5.10.1/DBIx/Class/Candy.pm line 265
BEGIN failed--compilation aborted at lib/Grimlock/Schema/Result/Session.pm line 9.
Compilation failed in require at /usr/local/share/perl/5.10.1/Class/C3/Componentised.pm line 150. at /usr/local/share/perl/5.10.1/Class/C3/Componentised.pm line 155
Compilation failed in require at /usr/local/share/perl/5.10.1/Module/Runtime.pm line 317.
 at reader DBIx::Class::Admin::schema (defined at /usr/local/share/perl/5.10.1/DBIx/Class/Admin.pm line 81) line 7
alnewkirk@alnewkirk:~/Repos/alnewkirk/Grimlock$

**Comment by dhoss** [comment]
i'll set up travis-ci to test on 5.10.1
